name: google_maps_markerclusterer
description: Creates and manages per-zoom-level clusters for large amounts of markers.
version: 0.1.2
homepage: https://github.com/reyerstudio/google-maps-markerclusterer
author: Stéphane Este-Gracias <sestegra@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  google_maps: ^3.3.0
  js_wrapping: ^0.5.0

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  html: ^0.13.0
  js_wrapping_generator: ^0.5.0
  test: ^1.3.0

#dependency_overrides:
#  js_wrapping:
#    path: ../dart-js-wrapping2/js_wrapping
#  js_wrapping_generator:
#    path: ../dart-js-wrapping/js_wrapping_generator
